<a href="https://colab.research.google.com/github/sharvarimhaske/python-basic-project-/blob/main/14_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
import numpy as np

arr = np.random.randint(10, 101, size=(5, 6))

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Total number of elements:", arr.size)
print("Data type:", arr.dtype)

Array:
 [[49 86 35 14 62 16]
 [47 99 49 34 88 69]
 [35 70 13 61 33 32]
 [49 99 37 50 63 30]
 [84 29 44 84 83 91]]
Shape: (5, 6)
Total number of elements: 30
Data type: int64


In [ ]:
import numpy as np

arr = np.random.randint(1, 51, size=20)

print("Array:", arr)
print("Minimum value:", np.min(arr))
print("Index of Minimum Value:", np.argmin(arr))
print("Maximum value:", np.max(arr))
print("Index of Maximum Value:", np.argmax(arr))
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

Array: [48 16  7 10  8  8 17 31 44 33 39 42 27  6 28 17 37 13 41  4]
Minimum value: 4
Index of Minimum Value: 19
Maximum value: 48
Index of Maximum Value: 0
Sum: 476
Mean: 23.8
Standard Deviation: 14.389579563003222


In [ ]:
import numpy as np

arr = np.random.randint(20, 81, size=(4, 5))

print("Matrix:\n", arr)

print("Minimum Value:", np.min(arr))
print("Maximum Value:", np.max(arr))
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

print("Row Sum:", np.sum(arr, axis=1))
print("Column Sum:", np.sum(arr, axis=0))

Matrix:
 [[71 73 54 33 41]
 [34 64 58 46 32]
 [20 40 49 40 69]
 [37 31 78 43 20]]
Minimum Value: 20
Maximum Value: 78
Sum: 933
Mean: 46.65
Standard Deviation: 16.90051774354857
Row Sum: [272 234 218 209]
Column Sum: [162 208 239 162 162]


In [ ]:
import numpy as np

arr = np.arange(1, 25)

print("Original Array:")
print(arr)

a = arr.reshape(4, 6)
print("\nReshape into (4,6):")
print(a)
print("Shape:", a.shape)

b = arr.reshape(3, 8)
print("\nReshape into (3,8):")
print(b)
print("Shape:", b.shape)

c = arr.reshape(2, 3, 4)
print("\nReshape into (2,3,4):")
print(c)
print("Shape:", c.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Reshape into (4,6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

Reshape into (3,8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

Reshape into (2,3,4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [ ]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print("Array:")
print(arr)

# First row
print("First Row:")
print(arr[0])

# Last column
print("Last Column:")
print(arr[:, -1])

# Center 2×2 submatrix
print("Center 2×2 Submatrix:")
print(arr[1:3, 1:3])

# Even numbers
print("Even Numbers:")
print(arr[arr % 2 == 0])

Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
First Row:
[10 20 30 40]
Last Column:
[ 40  80 120]
Center 2×2 Submatrix:
[[ 60  70]
 [100 110]]
Even Numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [ ]:
import numpy as np

arr = np.random.randint(1, 101, size=(5, 5))

print("Original Matrix:")
print(arr)

print("Diagonal Elements:")
print(np.diag(arr))

print("Elements Greater Than 50:")
print(arr[arr > 50])

arr[arr < 30] = 0

print("Modified Matrix:")
print(arr)

Original Matrix:
[[ 3 74 33 85 28]
 [40 88 19 55  1]
 [93 72 38 67 71]
 [ 2 45 91  9 36]
 [44 12 84 89 35]]
Diagonal Elements:
[ 3 88 38  9 35]
Elements Greater Than 50:
[74 85 88 55 93 72 67 71 91 84 89]
Modified Matrix:
[[ 0 74 33 85  0]
 [40 88  0 55  0]
 [93 72 38 67 71]
 [ 0 45 91  0 36]
 [44  0 84 89 35]]


In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array a:", a)
print("Array b:", b)

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Element-wise Power:", a ** b)

Array a: [10 20 30 40]
Array b: [1 2 3 4]
Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Element-wise Power: [     10     400   27000 2560000]


In [ ]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
elementwise = A * B
matrix_mult = A @ B
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nElement-wise Multiplication:")
print(elementwise)
print("\nMatrix Multiplication:")
print(matrix_mult)




Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
import numpy as np

arr = np.random.randn(6, 6)

print("Original Matrix:")
print(arr)

print("\nShape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

max_index = np.unravel_index(np.argmax(arr), arr.shape)
min_index = np.unravel_index(np.argmin(arr), arr.shape)

print("\nIndex of Maximum Value:", max_index)
print("Maximum Value:", arr[max_index])

print("\nIndex of Minimum Value:", min_index)
print("Minimum Value:", arr[min_index])

submatrix = arr[:3, :3]

print("\nTop-Left 3x3 Submatrix:")
print(submatrix)


arr[arr < 0] = np.abs(arr[arr < 0])

print("\nModified Matrix (Negative values replaced):")
print(arr)

print("\nMean of Modified Matrix:", np.mean(arr))

Original Matrix:
[[ 0.80580924  0.75380874 -0.88447376  0.61390409  0.0259697  -0.91729786]
 [-0.8709952  -1.94573028 -0.95847786  2.03850684 -0.48753544  0.10805954]
 [ 0.01762048  1.41903598 -0.32559124  1.60173883 -0.49525236  0.90864723]
 [-1.93799729  1.71744939  2.23216382 -1.14807074 -0.13501599 -0.37873378]
 [ 0.42803866 -0.69820526 -1.00401862  0.35948035 -0.49564867 -0.1281263 ]
 [ 1.34761092  0.64910512 -0.74744507  1.31084843 -0.70367091 -0.60500642]]

Shape: (6, 6)
Size: 36
Data Type: float64

Index of Maximum Value: (np.int64(3), np.int64(2))
Maximum Value: 2.2321638199219422

Index of Minimum Value: (np.int64(1), np.int64(1))
Minimum Value: -1.9457302755844688

Top-Left 3x3 Submatrix:
[[ 0.80580924  0.75380874 -0.88447376]
 [-0.8709952  -1.94573028 -0.95847786]
 [ 0.01762048  1.41903598 -0.32559124]]

Modified Matrix (Negative values replaced):
[[0.80580924 0.75380874 0.88447376 0.61390409 0.0259697  0.91729786]
 [0.8709952  1.94573028 0.95847786 2.03850684 0.48753544 0.

In [ ]:
import numpy as np

# Step 1: Generate random marks (10 students × 5 subjects)
marks = np.random.randint(30, 101, (10, 5))

# Step 2: Print marks
print("Marks of students:\n", marks)

# Step 3: Total marks for each student
total_marks = np.sum(marks, axis=1)
print("\nTotal Marks of each student:\n", total_marks)

# Step 4: Average marks for each student
average_marks = np.mean(marks, axis=1)
print("\nAverage Marks of each student:\n", average_marks)

# Step 5: Find highest and lowest scoring students
top_student = np.argmax(total_marks)
low_student = np.argmin(total_marks)

print("\nTop student index:", top_student)
print("Lowest student index:", low_student)

# Step 6: Class statistics
class_mean = np.mean(marks)
class_std = np.std(marks)

print("\nClass Mean:", class_mean)
print("Class Standard Deviation:", class_std)

# Step 7: Reshape array (demo purpose)
reshaped = marks.reshape(5, 10)
print("\nReshaped array (5x10):\n", reshaped)

# Step 8: Top 3 students
top3_indices = np.argsort(total_marks)[-3:]
top3_marks = marks[top3_indices]

print("\nTop 3 students' marks:\n", top3_marks)
print("Top 3 student indices:", top3_indices)

Marks of students:
 [[ 40  63  42  78  81]
 [ 68  64  54  97  34]
 [ 55  47  94  88  35]
 [ 79  88  38  72  75]
 [ 99 100  99  51  74]
 [ 44  54  79  60  37]
 [ 99  96  46  98  32]
 [ 75  33  70  43 100]
 [ 90  81  57  89  83]
 [ 76  52  73  74  82]]

Total Marks of each student:
 [304 317 319 352 423 274 371 321 400 357]

Average Marks of each student:
 [60.8 63.4 63.8 70.4 84.6 54.8 74.2 64.2 80.  71.4]

Top student index: 4
Lowest student index: 5

Class Mean: 68.76
Class Standard Deviation: 21.33219163611653

Reshaped array (5x10):
 [[ 40  63  42  78  81  68  64  54  97  34]
 [ 55  47  94  88  35  79  88  38  72  75]
 [ 99 100  99  51  74  44  54  79  60  37]
 [ 99  96  46  98  32  75  33  70  43 100]
 [ 90  81  57  89  83  76  52  73  74  82]]

Top 3 students' marks:
 [[ 99  96  46  98  32]
 [ 90  81  57  89  83]
 [ 99 100  99  51  74]]
Top 3 student indices: [6 8 4]
