<a href="https://colab.research.google.com/github/sharvarimhaske/python-basic-project-/blob/main/numpy-array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
import numpy as np


arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("1D Array:")
print(arr1)
print("Shape:", arr1.shape)
print("Data Type:", arr1.dtype)

print("\n2D Array:")
print(arr2)
print("Shape:", arr2.shape)
print("Data Type:", arr2.dtype)

1D Array:
[10 20 30 40 50]
Shape: (5,)
Data Type: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int64


In [3]:
import numpy as np


a = np.zeros(8)


b = np.ones((4, 4))

c = np.zeros((3, 3))

print("1D Array of 8 Zeros:")
print(a)

print("\n4x4 Array of Ones:")
print(b)

print("\n3x3 Matrix of Zeros:")
print(c)

1D Array of 8 Zeros:
[0. 0. 0. 0. 0. 0. 0. 0.]

4x4 Array of Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
import numpy as np


a = np.arange(0, 21, 1)


b = np.arange(10, 51, 2)


c = np.arange(5, 101, 5)

print("Numbers from 0 to 20:")
print(a)

print("\nEven Numbers from 10 to 50:")
print(b)

print("\nNumbers from 5 to 100 (Step 5):")
print(c)

Numbers from 0 to 20:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Even Numbers from 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

Numbers from 5 to 100 (Step 5):
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [5]:
import numpy as np


a = np.linspace(0, 5, 10)


b = np.linspace(10, -10, 15)

print("10 Equally Spaced Numbers between 0 and 5:")
print(a)
print("Length:", len(a))

print("\n15 Equally Spaced Numbers between 10 and -10:")
print(b)
print("Length:", len(b))

10 Equally Spaced Numbers between 0 and 5:
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10

15 Equally Spaced Numbers between 10 and -10:
[ 10.           8.57142857   7.14285714   5.71428571   4.28571429
   2.85714286   1.42857143   0.          -1.42857143  -2.85714286
  -4.28571429  -5.71428571  -7.14285714  -8.57142857 -10.        ]
Length: 15


In [6]:
import numpy as np

a = np.random.rand(10)

b = np.random.randn(3, 3)


c = np.random.randint(10, 51, (4, 5))

print("Random Numbers (0 to 1):")
print(a)

print("\n3x3 Standard Normal Random Matrix:")
print(b)

print("\n4x5 Random Integers (10 to 50):")
print(c)

Random Numbers (0 to 1):
[0.04805559 0.28567408 0.92935371 0.85766179 0.22723755 0.28403419
 0.29982462 0.83348582 0.5205753  0.52929796]

3x3 Standard Normal Random Matrix:
[[-0.18895732  2.63271036  1.85712105]
 [-0.14897829 -0.39639529  0.30320789]
 [-0.74364013  1.30644486  0.52340706]]

4x5 Random Integers (10 to 50):
[[39 32 43 48 17]
 [40 35 38 35 47]
 [21 16 18 10 28]
 [30 26 34 41 23]]


In [7]:
import numpy as np

v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])

print("Vector 1:", v1)
print("Vector 2:", v2)

print("\nAddition:")
print(v1 + v2)

print("\nSubtraction:")
print(v1 - v2)

print("\nElement-wise Multiplication:")
print(v1 * v2)

print("\nDot Product:")
print(np.dot(v1, v2))

Vector 1: [2 4 6 8]
Vector 2: [1 3 5 7]

Addition:
[ 3  7 11 15]

Subtraction:
[1 1 1 1]

Element-wise Multiplication:
[ 2 12 30 56]

Dot Product:
100


In [8]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix Addition:")
print(A + B)

print("\nMatrix Multiplication:")
print(A @ B)


print("\nElement-wise Multiplication:")
print(A * B)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [9]:
import numpy as np


arr = np.random.randint(1, 101, (4, 4))

print("4x4 Random Matrix:")
print(arr)

print("\nShape:", arr.shape)
print("Dimension (ndim):", arr.ndim)
print("Total Elements (size):", arr.size)
print("Data Type:", arr.dtype)
print("Minimum Value:", arr.min())
print("Maximum Value:", arr.max())

4x4 Random Matrix:
[[34 73 19 90]
 [70 67 40  5]
 [38 18 96 77]
 [80  1 36  8]]

Shape: (4, 4)
Dimension (ndim): 2
Total Elements (size): 16
Data Type: int64
Minimum Value: 1
Maximum Value: 96


In [10]:
import numpy as np

arr = np.random.randint(1, 51, 20)

print("Original 1D Array:")
print(arr)

matrix = arr.reshape(4, 5)

print("\n4x5 Matrix:")
print(matrix)

print("\nSum:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Standard Deviation:", np.std(matrix))

print("\nMaximum Value in Each Row:")
print(np.max(matrix, axis=1))

Original 1D Array:
[46  3  2 21 21  3 43 23 31 19 25 17 47 33 43  3  2 46 40  5]

4x5 Matrix:
[[46  3  2 21 21]
 [ 3 43 23 31 19]
 [25 17 47 33 43]
 [ 3  2 46 40  5]]

Sum: 473
Mean: 23.65
Standard Deviation: 16.353210693927966

Maximum Value in Each Row:
[46 43 47 46]


In [11]:
import numpy as np

try:

    n = int(input("Enter how many random numbers you want to generate: "))

    if n <= 0:
        print("Please enter a positive number.")

    else:

        arr = np.random.randint(10, 101, n)

        print("\nGenerated Array:")
        print(arr)


        print("\nMean:", np.mean(arr))
        print("Median:", np.median(arr))
        print("Standard Deviation:", np.std(arr))
        print("Minimum:", np.min(arr))
        print("Maximum:", np.max(arr))


        if n % 2 == 0:
            matrix = arr.reshape(2, n // 2)

            print("\nReshaped 2D Array:")
            print(matrix)

            print("\nRow-wise Sum:")
            print(np.sum(matrix, axis=1))

        else:
            print("\nCannot reshape into a 2D array with 2 rows because the number of elements is odd.")

except ValueError:
    print("Invalid input! Please enter an integer.")

Enter how many random numbers you want to generate: 6

Generated Array:
[50 59 19 88 38 67]

Mean: 53.5
Median: 54.5
Standard Deviation: 21.777281740382566
Minimum: 19
Maximum: 88

Reshaped 2D Array:
[[50 59 19]
 [88 38 67]]

Row-wise Sum:
[128 193]
